### ISSUE TITLE
(core): inconsistency in pinning cdk lib vs alpha dependencies

### ISSUE THREAD

**Issue by jaidisido** [awslabs/aws-ddk#106]
### Describe the bug

[Alpha cdk dependencies](https://github.com/awslabs/aws-ddk/blob/main/core/pyproject.toml#L38) set pinned to major in pyproject. At the same time, [cdk-lib](https://github.com/awslabs/aws-ddk/blob/main/cli/aws_ddk/data/project_templates/ddk_app/%7B%7Bcookiecutter.directory_name%7D%7D/requirements.txt#L1) is pinned to a specific **minor** version.

As a result, when a user runs `pip install -r requirements`, they would see a potential ERROR where alpha packages are being installed to the latest version while cdk lib remains pinned. Eventually, the two set of libraries would be so adrift that it would cause pip to fail the install

### How to Reproduce

Run
```
pip install -r requirements.txt
```
and notice the error

### Environment

```
Provide your `pip list` output, particularly the version of the AWS DDK library you used. Providing this information may significantly improve resolution times.
```

### OS

Mac

### Python version

3.8

### AWS DDK version

0.3.1

**Comment by kukushking** [comment]
```
aws-cdk-lib = "^2.20.0"
"aws-cdk.aws-glue-alpha" = "^2.20.0a0"
"aws-cdk.aws-kinesisfirehose-alpha" = "^2.20.0a0"
"aws-cdk.aws-kinesisfirehose-destinations-alpha" = "^2.20.0a0"
```
They're all pinned in the same way. Am I missing something here?
