### ISSUE TITLE
(core) Airflow (MWWA) data pipeline stage

### ISSUE THREAD

**Issue by kukushking** [awslabs/aws-ddk#109]
**Is your feature request related to a problem? Please describe.**
DDK Airflow integration

**Describe the solution you'd like**
I'd like to be able to kickoff MWWA DAG's in DDK DataPipelines. A stage should kickoff the DAG and wait for it to complete.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

*P.S. Please Don't attach files. Add code snippets directly in the message body instead.*

**Comment by anmolsgandhi** [comment]
I would like to bump this up as we have a feature request for a customer to add this as a data pipeline stage
