### ISSUE TITLE
Glue job role failed to execute job when security_configuration = None 

### ISSUE THREAD

**Issue by nehatha8289** [awslabs/aws-ddk#124]
### Describe the bug

Getting following error 

![image](https://user-images.githubusercontent.com/90688777/174240812-38aef785-d09c-4634-b7cb-921582e63bec.png)

Code snippet:

GlueFactory.job(
            scope=self,
            id="<id>",
            environment_id=environment_id,
            security_configuration = None,
            executable=JobExecutable.of(
                glue_version=GlueVersion.V3_0,
                language=JobLanguage.PYTHON,
                script=Code.from_asset("<path>"),
                type=JobType.ETL,
            ),
        )

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Code sample:

GlueFactory.job(
            scope=self,
            id="<id>",
            environment_id=environment_id,
            security_configuration = None,
            executable=JobExecutable.of(
                glue_version=GlueVersion.V3_0,
                language=JobLanguage.PYTHON,
                script=Code.from_asset("<path>"),
                type=JobType.ETL,
            ),
        )

### Environment

```
Provide your `pip list` output, particularly the version of the AWS DDK library you used. Providing this information may significantly improve resolution times.
```
aws-cdk-lib==2.27.0
aws_ddk_core==0.4.1

### OS

Glue 3.0 

### Python version

Python 3

### AWS DDK version

0.4.1

**Comment by malachi-constant** [comment]
CLEANUP: Merged PR above seems to handle, closing.
