### ISSUE TITLE
Revirew & upgrade CDK alpha packages to official

### ISSUE THREAD

**Issue by kukushking** [awslabs/aws-ddk#189]
We still rely on a couple of alpha packages:
`
"aws-cdk.aws-glue-alpha" = "^2.20.0a0"
"aws-cdk.aws-kinesisfirehose-alpha" = "^2.20.0a0"
"aws-cdk.aws-kinesisfirehose-destinations-alpha" = "^2.20.0a0"
`

Looks like official [kinesisfirehose](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kinesisfirehose-readme.html) package is available. 

We should review which alpha packages we can deprecate and update the code to use official CDK packages.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by malachi-constant** [comment]
@kukushking The package linked is just L1 constructs, so we'll still need to rely on the alpha packages. I checked the other two and same case for them as well.

> There are no official hand-written ([L2](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_lib)) constructs for this service yet. Here are some suggestions on how to proceed:

**Comment by malachi-constant** [comment]
I'll take the opportunity to do upgrade cdk -> `2.54.0` though.
