### ISSUE TITLE
core: RedshiftDataApi Transform Stage

### ISSUE THREAD

**Issue by malachi-constant** [awslabs/aws-ddk#201]
* A stage that has a step function that can run a fixed or dynamic sql query against redshift (UNLOAD/COPY/SELECT) using no/low code with SDK integration of step function of redshift data-api
        * If query is passed to the stage then a step function is created executing only that query 
        * if query is not passed, then it needs to be passed dynamically using step function event message
    * *Potential Steps*
        * step1: Execute statement (query passed)
        * step2: DescribeStatment to get execution id
        * step3: Wait for execution to complete

**Comment by HKAgrwl** [comment]
can you assign this issue to me?

**Comment by malachi-constant** [comment]
@HKAgrwl sure, you are more than welcome to implement and open a PR for review. Until now, we have been writing CDK constructs in python but will be moving to typescript in the very near-term. You can use either, but if you want to go with typescript we are working into this branch: [`typescript-conversion`](https://github.com/awslabs/aws-ddk/tree/typescript-conversion)
