### ISSUE TITLE
`pandas_sdk_layer` Uses incorrect layer version us-east-1 LambdaLayer

### ISSUE THREAD

**Issue by noah-paige** [awslabs/aws-ddk#255]
### Describe the bug

When using the `pandas_sdk_layer()` for a Lambda Layer added to a Lambda Function deployed in `us-east-1` the utility does not attach that latest version of AWS SDK for pandas and instead adds the Lambda layer suffixed with `:1`

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

1. Use SQSToLambda Stage when defining your DDK Application and pass `layers=[pandas_sdk_layer()]`
2. Deploy the DDK App to us-east-1 region and check the lambda layer version of SDK for pandas attached

### Expected behavior

Using the `pandas_sdk_layer()` to add a lambda layer should use the latest version unless a verison is explicitly specified

### Environment

```
Provide your `pip list` output, particularly the version of the AWS DDK library you used. Providing this information may significantly improve resolution times.
```

### OS

N/A

### Python version

3.9

### AWS DDK version

0.6.2

**Comment by malachi-constant** [comment]
This feature is on hold in `1.x.x`, closing this in favor of #212
