### ISSUE TITLE
ts: JSII not converting `memorySize` to `memory_size` when packaging python

### ISSUE THREAD

**Issue by malachi-constant** [awslabs/aws-ddk#271]
### Describe the bug

**Output of LambdaDefaults.function_props()**
```{'memorySize': 256, 'timeout': <aws_cdk.Duration object at 0x1138534f0>, 'code': <aws_cdk.aws_lambda.InlineCode object at 0x1138492e0>, 'handler': 'lambda_function.lambda_handler', 'runtime': <aws_cdk.aws_lambda.Runtime object at 0x113882070>}```

### How to Reproduce

```
from aws_ddk_core import, LambdaDefaults


print(LambdaDefaults.function_props(
        code=lmbda.Code.from_inline("def lambda_handler(event, context): pass"),
        handler="lambda_function.lambda_handler",
        runtime=lmbda.Runtime.PYTHON_3_9
    ))
```

### Environment

```
Provide your `pip list` output, particularly the version of the AWS DDK library you used. Providing this information may significantly improve resolution times.
```

### OS

Mac

### Python version

3.9

### AWS DDK version

1.0.0b1

**Comment by anmolsgandhi** [comment]
This also happens with KMSDefaults with enableKeyRotation and i am very sure this will to all attributes with lower camel case in all the defaults where JSII doesnt convert them @malachi-constant
