### ISSUE TITLE
bug: feature mismatch between ts and python for configurator 

### ISSUE THREAD

**Issue by anmolsgandhi** [awslabs/aws-ddk#312]
### Describe the bug

While testing examples for aws-ddk 1.0.0b1, there was a breaking changes for Configurator (getEnvConfig) as it now returns EnvironmentConfiguration instead of all values under the environment_id key

**Minor**: 
Now while using get_env_config() in PY version to extract values, i have to use `env_conf = Configurator.get_env_config(....)._values` to unpack values. Not a major issue but wanted to highlight it

**MisMatch**:
As seen here in [examples]( https://github.com/aws-samples/aws-ddk-examples/blob/release-1.0.0/sdlf-ddk-lightweight/typescript/bin/sdlf.ts) l78, l90 for TS. It uses `getConfig(..)` which is not available to use in PY version

**Functionality change:**
Initially the get_env_config was able to give me everything that i needed to get all values when passed a environment_id as a key but not it returns set keys and will be an issue if user puts keys outside of defined configuration. e.g 

```
{
  "environments": {
    "cicd": {
      "account": "111111111111",
      "region": "us-east-1",
      "repository": "sdlf-ddk-example",
      "cicd_enabled": true
    },
    "dev": {
      "account": "111111111111",
      "region": "us-east-1",
      "name": "Development",
      "resource_prefix": "sdlf",
      "manual_approvals": false,
      "data_pipeline_parameters": {
        "org": "aws",
        "app": "datalake"
      }
    }
  }
}
```
The Configurator.get_env_config(...,"dev") would initially return 

```
{
      "account": "111111111111",
      "region": "us-east-1",
      "name": "Development",
      "resource_prefix": "sdlf",
      "manual_approvals": false,
      "data_pipeline_parameters": {
        "org": "aws",
        "app": "datalake"
}
```

after change in 1.0.0b1 it will be an object of  EnvironmentConfiguration() with only selected keys mentioned [here](https://github.com/awslabs/aws-ddk/blob/2c8e3eb358c383f2cdc05c02ced963f2e3339b95/src/config/configurator.ts#L12)

I am currently handing this by defining Configurator class and then using the get_config_attribute() method. 

I believe if we allow non defined keys in escape hatch then get_env_config should be able to give all keys under the environment_id instead of only the predefined one. Also is there any benefits of returning an object instead of dict directly as in PY we will forced to use _values to unpack values unless there is another way to do it

### How to Reproduce

use the get_env_config() method in PY version to understand most of the above mentioned issues

### Environment

```
Provide your `pip list` output, particularly the version of the AWS DDK library you used. Providing this information may significantly improve resolution times.
```

### OS

Mac

### Python version

3.9

### AWS DDK version

1.0.0b1

**Comment by malachi-constant** [comment]
Hi @anmolsgandhi I've added a [PR](https://github.com/awslabs/aws-ddk/pull/315) that touches on some of the things you've called out. 

Namely,
- Adding `getConfig` as a static method so it can be used after JSII assembly
- Adds `props` to our Configuration types to support additional properites in both global and environment based configuration for Configurator.


I think the typing question goes back to a bit of a larger discussion. Maybe @LeonLuttenberger can add more color as he raised the [initial PR](https://github.com/awslabs/aws-ddk/pull/308), but I think we should aim to keep `Configurator` as straightforward as possible and less open-ended than `Config` in `0.x.x`. I think in your case above you should be ok to just utilize `props` in the example, but in more complex customer use cases I'd like to encourage custom approaches over extenstion of `Configurator`. 

As far as unpacking values with `_values` i'm not aware of any other way to accomplish it right now. My understanding is it's a limitation of how JSII packages object types. Maybe @LeonLuttenberger has additional insight.

**Comment by anmolsgandhi** [comment]
I think this is good, most of the things can be achieved with the combination of features we have provided. I have also demonstrated the use of different functionalities with configurator in our examples which should do it.
