### ISSUE TITLE
config: get_env_config() should have `config_path` as optional

### ISSUE THREAD

**Issue by Rizxcviii** [awslabs/aws-ddk#342]
Rather than needing to specify the same config throughout our program, let the parameter `config_path` be optional, and be default assigned. From what I've viewed from the source code, the static method uses the `get_config()` method, which uses a fixed path if not specified from the end user.

- The version of our code being used
  - 1.0.0

**Comment by malachi-constant** [comment]
@Rizxcviii Thanks for opening.. I'm in agreement. Fix started.
