### ISSUE TITLE
config: Bootstrap within multiple different regions for different environments

### ISSUE THREAD

**Issue by Rizxcviii** [awslabs/aws-ddk#345]
Is there currently a way to point/deploy to a different region when bootstrapping. I'm currently attempting to point our existing bootstrap stack that is located within `eu-west-1` in our DDK app. However, I'm not seeing a configuration to do so.
For our specific use case, our prod region is bootstrapped in `eu-west-2`, and our dev region is bootstrapped in `eu-west-1`. However, both regions are pointing to `eu-west-2`.

- A reproducible test case or series of steps
  - Have an existing bootstrapped environment in another region
- The version of our code being used
  - 1.0.0
- Anything unusual about your environment or deployment
  - Bootstrapped during the 0.x release (specifically 0.4.1)

**Comment by malachi-constant** [comment]
Thanks @Rizxcviii i've taken a closer look and this is indeed a bug that boils down to [appending account ids and regions to stack synthesizer resources](https://github.com/awslabs/aws-ddk/blob/a25a879c4c59a7004748a48f0b1ef97d9e2834fb/src/config/configurator.ts#L128) that do not come from configuration. 

With the configuration 
```json
{
  "environments": {
    "dev": {
      "bootstrap": {
        "prefix": "ddk"
      },
      "account": "22222222222",
      "region": "us-east-1"
    },
    "prod": {
      "bootstrap": {
        "prefix": "ddk"
      },
      "account": "222222222222",
      "region": "us-west-2"
    }
  }
}
```

```javascript
import * as cdk from "aws-cdk-lib";
import * as ddk from "aws-ddk-core";


const app = new cdk.App();

const devStack = new ddk.BaseStack(app, "my-dev-stack", {
  environmentId: "dev",
  stackName: "MyDevStack",
});

new ddk.Configurator(devStack, "./ddk.json", "dev")

const prodStack = new ddk.BaseStack(app, "my-prod-stack", {
  environmentId: "prod",
  stackName: "MyProdStack",
});
new ddk.Configurator(prodStack, "./ddk.json", "prod")


console.log(devStack.synthesizer)
console.log(prodStack.synthesizer)
```

#### Prod Stack Synthesizer values are using wrong region
```shell
qualifier: 'hnb659fds',
  bucketName: 'ddk-prod-hnb659fds-assets-032118170130-us-east-1',
  repositoryName: 'cdk-hnb659fds-container-assets-${AWS::AccountId}-${AWS::Region}',
  _deployRoleArn: 'arn:aws:iam::032118170130:role/ddk-prod-hnb659fds-deploy-032118170130-us-east-1',
  _cloudFormationExecutionRoleArn: 'arn:aws:iam::032118170130:role/ddk-prod-hnb659fds-cfn-exec-032118170130-us-east-1',
  fileAssetPublishingRoleArn: 'arn:aws:iam::032118170130:role/ddk-prod-hnb659fds-file-publish-032118170130-us-east-1',
  imageAssetPublishingRoleArn: 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/cdk-hnb659fds-image-publishing-role-${AWS::AccountId}-${AWS::Region}',
  lookupRoleArn: 'arn:aws:iam::032118170130:role/ddk-prod-hnb659fds-lookup-032118170130-us-east-1',
  bucketPrefix: '',
  dockerTagPrefix: '',
  bootstrapStackVersionSsmParameter: '/ddk/prod/hnb659fds/bootstrap-version'
```

Will open a PR to address shortly.
