### ISSUE TITLE
CICD: adding environment variable at synth stage

### ISSUE THREAD

**Issue by Rizxcviii** [awslabs/aws-ddk#374]
According to the [AWS documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock), I need to add a an environment variable during the synthesis stage, to use `aws-lambda-python`. However I'm not noticing an obvious way to do so.
Is there another place where I am meant to put this variable? Or has this not yet been implemented?

**Comment by malachi-constant** [comment]
At the moment there is an escape hatch that allow you to pass your own synth action to the pipeline

```javascript
.addSynthAction({synthAction: ...})
```

I believe the snippet in the docs is outdated as I can't find any construct titled `CdkPipeline()`

```javascript
const pipeline = new pipelines.CdkPipeline(this, 'MyPipeline', {
  cloudAssemblyArtifact,
  synthAction: pipelines.SimpleSynthAction.standardNpmSynth({
    sourceArtifact,
    cloudAssemblyArtifact,
    environment: {
      privileged: true,
    },
  }),
});
```

However, we should be able to pass `env` as a parameter to the [`CodeBuildStep`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodeBuildStep.html#buildenvironment) created within our construct. I'll get started on a PR to get that working tomorrow. Above is the workaround for now.

**Comment by Rizxcviii** [comment]
I checked it out further, it might be in the `.build_pipeline()` function where you can parse `docker_enabled_for_synth`, which is the variable to use when making use of a `CodeBuildStep` construct.

**Comment by malachi-constant** [comment]
If that's the property you need you should able to pass that into `.build_pipeline()` with the current construct.

[API Docs](https://constructs.dev/packages/aws-ddk-core/v/1.0.1/api/CICDPipelineStack?lang=python#buildPipeline)
