### ISSUE TITLE
config: Configurator interfaces marked as required, but default value is said to be assigned

### ISSUE THREAD

**Issue by Rizxcviii** [awslabs/aws-ddk#416]
When using the `get_environment()` function, I'm still required to specify the `config_path` prop, even though the documentation states: 
> Relative path to config file. Defaults to './ddk.json'

It appears to still be required within the interface design. The same goes for `GetTagProps`

```ts
export interface GetTagsProps {
  /**
   * Relative path to config file. Defaults to './ddk.json'
   */
  readonly configPath: string;
  /**
   * Environment identifier
   */
  readonly environmentId?: string;
}

export interface GetEnvironmentProps {
  /**
   * Relative path to config file. Defaults to './ddk.json'
   */
  readonly configPath: string;
  /**
   * Environment identifier.
   */
  readonly environmentId?: string;
}
```

**Comment by malachi-constant** [comment]
Yep, good catch, the default behavior is happening within `getConfig()` updating with fix now.
