### ISSUE TITLE
MWAATriggerDagsStage does not pass runtime args/parameters to MWAA dag

### ISSUE THREAD

**Issue by devansh-gandhi** [awslabs/aws-ddk#428]
### Issue Description

The MWAATriggerDagsStage does not pass the sfn event input to the MWAA dag. I am working on a usecase wherein I would like to pass the sfn input (S3 bucket/key and other metadata) to the MWAA dag for further processing. This could be an enhancement wherein the sfn input is passed to the MWAA dag.

### Expected Behavior
MWAATriggerDagsStage passes the sfn input as runtime arguments/parameters to the MWAA dag. 

### Actual Behavior

MWAA dag is triggered with no additional runtime arguments/parameters passed. 

### Steps to Reproduce
1. Deploy a MWAAEnvironment and a MWAATriggerDagsStage
2. Trigger MWAATriggerDagsStage sfn with input paramters

### Additional Information

I would be willing to work on this issue.

**Comment by anmolsgandhi** [comment]
Hello Devansh, appreciate you opening the issue; if you've already tackled it, kindly create a pull request.

**Comment by devansh-gandhi** [comment]
Hi Anmol, Yes I can open a pull request.
