### ISSUE TITLE
API Reference link is a 404

### ISSUE THREAD

**Issue by stevebanik** [awslabs/aws-ddk#480]
https://awslabs.github.io/aws-ddk/release/stable/api/index

**Comment by malachi-constant** [comment]
@stevebanik Everthing `>=1.0.0` should route to [constructs hub](https://constructs.dev/packages/aws-ddk-core/v/1.3.1?lang=typescript). That would be an invalid url. 

For example clicking the API Docs link in docs should take you to Constructs hub.
<img width="905" alt="Screenshot 2023-12-26 at 11 25 11 AM" src="https://github.com/awslabs/aws-ddk/assets/6465221/7440dcda-acee-48c7-9857-f23a118af802">
