### ISSUE TITLE
(core): `add_notifications` method does not send notifications as expected

### ISSUE THREAD

**Issue by jaidisido** [awslabs/aws-ddk#62]
### Describe the bug

`add_notifications` method in `CICDPipelineStack` creates the CodeStar notification but no notification is sent when the CodePipeline pipeline fails 

### How to Reproduce

1. Create a DDK CICD pipeline and add notifications
```
CICDPipelineStack(
...
.add_notifications()
```
2. An SNS topic should be created. Subscribe your email address to it
3. Fail the pipeline. The user expects an email to be sent but it never arrives

### Expected behavior

An email is sent when the Pipeline fails

### Environment

```
Provide your `pip list` output, particularly the version of the AWS DDK library you used. Providing this information may significantly improve resolution times.
```

### OS

Mac

### Python version

3.7

### AWS DDK version

0.2.1

**Comment by malachi-constant** [comment]
I imagine there's some issues with the SNS topic policy created, will investigate. Thanks for identifying..

**Comment by malachi-constant** [comment]
Hmm @jaidisido I'm not able to replicate
<img width="1393" alt="Screen Shot 2022-03-25 at 3 57 19 PM" src="https://user-images.githubusercontent.com/6465221/160212455-9ab4fb7d-3b78-460f-bfb3-5316ef0a434a.png">
<img width="1359" alt="Screen Shot 2022-03-25 at 3 58 04 PM" src="https://user-images.githubusercontent.com/6465221/160212631-b0df82ca-2161-4518-be85-486e942a513b.png">

**Comment by malachi-constant** [comment]
Functionality confirmed working, unable to replicate.
