### ISSUE TITLE
(core) sfn factory - add json definition

### ISSUE THREAD

**Issue by kukushking** [awslabs/aws-ddk#69]
**Is your idea related to a problem? Please describe.**

**Describe the solution you'd like**

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by malachi-constant** [comment]
Does this need to be reopened and kept in the backlog @kukushking ?

**Comment by kukushking** [comment]
Yeah, good catch, we should keep this open. 

Most likely we'll have to just wait for the functionality available in CDK before we add a parameter for that in our construct.

**Comment by malachi-constant** [comment]
Sfn Factory deprecated
